[package]
name = "icu4x_segmenter_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
icu_segmenter = { version = "1.5", features = ["compiled_data"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

