# New file
name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Type check popup
        run: npm run typecheck:popup

      - name: Run unit tests
        run: npm test -- --ci --reporters=default
        env:
          CI: true

      - name: Build dist
        run: npm run build

      - name: Build ZIP artifact
        run: npm run build:zip

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: qwen-translator-zip
          path: dist/*.zip

  e2e-smoke:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: .

      - name: Install Playwright (Chromium + deps)
        run: npx playwright install --with-deps chromium

      - name: Start static server
        run: |
          nohup npx http-server . -p 8080 &
          for i in {1..60}; do
            curl -sSf http://127.0.0.1:8080 >/dev/null && break || sleep 1;
          done

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

  automerge:
    needs: [build-and-test, e2e-smoke]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
