name: SBOM

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npx -y @cyclonedx/cdxgen -o sbom.json -r .
      - uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

